import { AppShell, Menu, Select, Tooltip, Notification, MantineThemeOverride } from '@mantine/core';
import { breakpointsWithPx } from './breakpoints-with-px';

export const myDefaultTheme: MantineThemeOverride = {
  breakpoints: breakpointsWithPx,
  colors: {
    violet: [
      'var(--color-violet-0)',
      'var(--color-violet-1)',
      'var(--color-violet-2)',
      'var(--color-violet-3)',
      'var(--color-violet-4)',
      'var(--color-violet-5)',
      'var(--color-violet-6)',
      'var(--color-violet-7)',
      'var(--color-violet-8)',
      'var(--color-violet-9)',
    ],
    lime: [
      'var(--color-lime-0)',
      'var(--color-lime-1)',
      'var(--color-lime-2)',
      'var(--color-lime-3)',
      'var(--color-lime-4)',
      'var(--color-lime-5)',
      'var(--color-lime-6)',
      'var(--color-lime-7)',
      'var(--color-lime-8)',
      'var(--color-lime-9)',
    ],
    grape: [
      'var(--color-grape-0)',
      'var(--color-grape-1)',
      'var(--color-grape-2)',
      'var(--color-grape-3)',
      'var(--color-grape-4)',
      'var(--color-grape-5)',
      'var(--color-grape-6)',
      'var(--color-grape-7)',
      'var(--color-grape-8)',
      'var(--color-grape-9)',
    ],
    dark: [
      'var(--color-dark-0)',
      'var(--color-dark-1)',
      'var(--color-dark-2)',
      'var(--color-dark-3)',
      'var(--color-dark-4)',
      'var(--color-dark-5)',
      'var(--color-dark-6)',
      'var(--color-dark-7)',
      'var(--color-dark-8)',
      'var(--color-dark-9)',
    ],
    cyan: [
      'var(--color-cyan-0)',
      'var(--color-cyan-1)',
      'var(--color-cyan-2)',
      'var(--color-cyan-3)',
      'var(--color-cyan-4)',
      'var(--color-cyan-5)',
      'var(--color-cyan-6)',
      'var(--color-cyan-7)',
      'var(--color-cyan-8)',
      'var(--color-cyan-9)',
    ],
    blue: [
      'var(--color-blue-0)',
      'var(--color-blue-1)',
      'var(--color-blue-2)',
      'var(--color-blue-3)',
      'var(--color-blue-4)',
      'var(--color-blue-5)',
      'var(--color-blue-6)',
      'var(--color-blue-7)',
      'var(--color-blue-8)',
      'var(--color-blue-9)',
    ],
    gray: [
      'var(--color-gray-0)',
      'var(--color-gray-1)',
      'var(--color-gray-2)',
      'var(--color-gray-3)',
      'var(--color-gray-4)',
      'var(--color-gray-5)',
      'var(--color-gray-6)',
      'var(--color-gray-7)',
      'var(--color-gray-8)',
      'var(--color-gray-9)',
    ],
    red: [
      'var(--color-red-0)',
      'var(--color-red-1)',
      'var(--color-red-2)',
      'var(--color-red-3)',
      'var(--color-red-4)',
      'var(--color-red-5)',
      'var(--color-red-6)',
      'var(--color-red-7)',
      'var(--color-red-8)',
      'var(--color-red-9)',
    ],
    green: [
      'var(--color-green-0)',
      'var(--color-green-1)',
      'var(--color-green-2)',
      'var(--color-green-3)',
      'var(--color-green-4)',
      'var(--color-green-5)',
      'var(--color-green-6)',
      'var(--color-green-7)',
      'var(--color-green-8)',
      'var(--color-green-9)',
    ],
    yellow: [
      'var(--color-yellow-0)',
      'var(--color-yellow-1)',
      'var(--color-yellow-2)',
      'var(--color-yellow-3)',
      'var(--color-yellow-4)',
      'var(--color-yellow-5)',
      'var(--color-yellow-6)',
      'var(--color-yellow-7)',
      'var(--color-yellow-8)',
      'var(--color-yellow-9)',
    ],
    purple: [
      'var(--color-purple-0)',
      'var(--color-purple-1)',
      'var(--color-purple-2)',
      'var(--color-purple-3)',
      'var(--color-purple-4)',
      'var(--color-purple-5)',
      'var(--color-purple-6)',
      'var(--color-purple-7)',
      'var(--color-purple-8)',
      'var(--color-purple-9)',
    ],
    orange: [
      'var(--color-orange-0)',
      'var(--color-orange-1)',
      'var(--color-orange-2)',
      'var(--color-orange-3)',
      'var(--color-orange-4)',
      'var(--color-orange-5)',
      'var(--color-orange-6)',
      'var(--color-orange-7)',
      'var(--color-orange-8)',
      'var(--color-orange-9)',
    ],
    pink: [
      'var(--color-pink-0)',
      'var(--color-pink-1)',
      'var(--color-pink-2)',
      'var(--color-pink-3)',
      'var(--color-pink-4)',
      'var(--color-pink-5)',
      'var(--color-pink-6)',
      'var(--color-pink-7)',
      'var(--color-pink-8)',
      'var(--color-pink-9)',
    ],
    teal: [
      'var(--color-teal-0)',
      'var(--color-teal-1)',
      'var(--color-teal-2)',
      'var(--color-teal-3)',
      'var(--color-teal-4)',
      'var(--color-teal-5)',
      'var(--color-teal-6)',
      'var(--color-teal-7)',
      'var(--color-teal-8)',
      'var(--color-teal-9)',
    ],
    indigo: [
      'var(--color-indigo-0)',
      'var(--color-indigo-1)',
      'var(--color-indigo-2)',
      'var(--color-indigo-3)',
      'var(--color-indigo-4)',
      'var(--color-indigo-5)',
      'var(--color-indigo-6)',
      'var(--color-indigo-7)',
      'var(--color-indigo-8)',
      'var(--color-indigo-9)',
    ],
  },
  cursorType: 'pointer',
  components: {
    Notification: Notification.extend({
      defaultProps: {
        withBorder: true,
      },
    }),
    AppShell: AppShell.extend({
      defaultProps: {
        padding: 0,
      },
    }),
    Select: Select.extend({
      defaultProps: {
        allowDeselect: false,
        withCheckIcon: false,
        clearable: true,
      },
    }),
    Menu: Menu.extend({
      defaultProps: {
        position: 'bottom-end',
      },
    }),
    Tooltip: Tooltip.extend({
      defaultProps: {
        multiline: true,
        maw: 300,
      },
    }),
  },
};
