name: Publish

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: "24"
          check-latest: true
          registry-url: "https://registry.npmjs.org"

      - name: Check npm version
        run: npm --version

      - name: Install
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test

      - name: Build
        run: npm run build

      - name: Pack dry run
        run: npm pack --dry-run

      - name: Publish
        run: npm publish --provenance
